[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  # Skicka igenom alla funktionsanrop och behåll HTTP-metoden (PUT, POST etc.)
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  # Fallback för Single-Page-Application
  from = "/*"
  to   = "/index.html"
  status = 200