[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  # Fallback för SPA – allt annat än funktioner hamnar på index.html
  from   = "/*"
  to     = "/index.html"
  status = 200